/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { FormEvent, useEffect, useState } from "react";
import { apiErrorMessage, readApiEnvelope } from "@/lib/admin-auth";
import styles from "./admin-simple-data.module.css";

type Lot = { id: string; title: string; slug: string; artist_name: string; starting_bid_cents: number; minimum_increment_cents: number; status: string };
type User = { id: string; name: string; email: string; active: boolean; roles: string[]; must_change_password: boolean };
type Privacy = { id: string; protocol: string; request_type: string; status: string; created_at: string; resolved_at: string | null };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);

export function AdminAuction() {
  const [items, setItems] = useState<Lot[]>([]), [error, setError] = useState(""), [csrf, setCsrf] = useState("");
  const [form, setForm] = useState({ title: "", slug: "", artist_name: "", starting_bid_cents: "", minimum_increment_cents: "" });
  async function load() { const [s, r] = await Promise.all([fetch("/api/v1/admin/auth/session", { credentials: "include" }), fetch("/api/v1/admin/auction-lots", { credentials: "include", cache: "no-store" })]); const sp = await readApiEnvelope<{ csrf_token: string }>(s), p = await readApiEnvelope<Lot[]>(r); if (!s.ok || !sp?.data) throw new Error(apiErrorMessage(sp, "Sessão expirada.")); if (!r.ok || !p?.data) throw new Error(apiErrorMessage(p, "Não foi possível carregar os lotes.")); setCsrf(sp.data.csrf_token); setItems(p.data); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "Erro ao carregar.")); }, []);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/v1/admin/auction-lots", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ ...form, starting_bid_cents: Number(form.starting_bid_cents), minimum_increment_cents: Number(form.minimum_increment_cents) }) }); const p = await readApiEnvelope<Lot>(response); if (!response.ok || !p?.data) return setError(apiErrorMessage(p, "Não foi possível criar o lote.")); setForm({ title: "", slug: "", artist_name: "", starting_bid_cents: "", minimum_increment_cents: "" }); await load(); }
  async function archive(id: string) { if (!window.confirm("Arquivar este lote?")) return; const response = await fetch(`/api/v1/admin/auction-lots/${id}`, { method: "DELETE", credentials: "include", headers: { "X-CSRF-Token": csrf } }); if (!response.ok) return setError("Não foi possível arquivar o lote."); setItems((current) => current.map((item) => item.id === id ? { ...item, status: "archived" } : item)); }
  return <section className={styles.section}><p className="eyebrow">Painel</p><h1>Leilão</h1><p className="lead">Cadastre e revise lotes. Lances continuam desativados pela configuração operacional.</p>{error && <div className="error-summary" role="alert">{error}</div>}<div className={styles.grid}><form className={styles.panel} onSubmit={create}><h2>Novo lote</h2><label>Título<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Slug<input required value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} /></label><label>Artista<input required value={form.artist_name} onChange={(e) => setForm({ ...form, artist_name: e.target.value })} /></label><label>Lance inicial (centavos)<input required type="number" min="0" value={form.starting_bid_cents} onChange={(e) => setForm({ ...form, starting_bid_cents: e.target.value })} /></label><label>Incremento (centavos)<input required type="number" min="1" value={form.minimum_increment_cents} onChange={(e) => setForm({ ...form, minimum_increment_cents: e.target.value })} /></label><button className="button" disabled={!csrf}>CRIAR LOTE</button></form><div className={styles.panel}><h2>Lotes</h2><ul className={styles.list}>{items.map((item) => <li className={styles.item} key={item.id}><strong>{item.title}</strong><span>{item.artist_name} · {money(item.starting_bid_cents)}</span><span className={styles.meta}>{item.status}</span><button className="button secondary" type="button" onClick={() => void archive(item.id)}>ARQUIVAR</button></li>)}</ul>{!items.length && <p className="muted">Nenhum lote cadastrado.</p>}</div></div></section>;
}

export function AdminUsers() {
  const [items, setItems] = useState<User[]>([]), [error, setError] = useState(""), [csrf, setCsrf] = useState(""), [form, setForm] = useState({ name: "", email: "", password: "", roles: "editor" });
  async function load() { const [s, r] = await Promise.all([fetch("/api/v1/admin/auth/session", { credentials: "include" }), fetch("/api/v1/admin/users", { credentials: "include", cache: "no-store" })]); const sp = await readApiEnvelope<{ csrf_token: string }>(s), p = await readApiEnvelope<User[]>(r); if (!s.ok || !sp?.data) throw new Error(apiErrorMessage(sp, "Sessão expirada.")); if (!r.ok || !p?.data) throw new Error(apiErrorMessage(p, "Não foi possível carregar os usuários.")); setCsrf(sp.data.csrf_token); setItems(p.data); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "Erro ao carregar.")); }, []);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/v1/admin/users", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ ...form, roles: [form.roles] }) }); const p = await readApiEnvelope<User>(response); if (!response.ok || !p?.data) return setError(apiErrorMessage(p, "Não foi possível criar o usuário.")); setForm({ name: "", email: "", password: "", roles: "editor" }); await load(); }
  async function deactivate(id: string) { if (!window.confirm("Desativar este usuário?")) return; const response = await fetch(`/api/v1/admin/users/${id}`, { method: "DELETE", credentials: "include", headers: { "X-CSRF-Token": csrf } }); if (!response.ok) return setError("Não foi possível desativar o usuário."); setItems((current) => current.map((item) => item.id === id ? { ...item, active: false } : item)); }
  return <section className={styles.section}><p className="eyebrow">Painel</p><h1>Usuários</h1><p className="lead">Contas individuais com papéis de menor privilégio e troca obrigatória da senha inicial.</p>{error && <div className="error-summary" role="alert">{error}</div>}<div className={styles.grid}><form className={styles.panel} onSubmit={create}><h2>Novo usuário</h2><label>Nome<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>E-mail<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Senha inicial<input required minLength={12} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Papel<select value={form.roles} onChange={(e) => setForm({ ...form, roles: e.target.value })}><option value="editor">Editor</option><option value="atendimento">Atendimento</option><option value="auditor">Auditor</option><option value="loja">Loja</option><option value="leilao">Leilão</option></select></label><button className="button" disabled={!csrf}>CRIAR USUÁRIO</button></form><div className={styles.panel}><h2>Contas</h2><ul className={styles.list}>{items.map((item) => <li className={styles.item} key={item.id}><strong>{item.name}</strong><span>{item.email}</span><span className={styles.meta}>{item.roles.join(", ")} · {item.active ? "Ativo" : "Inativo"}</span>{item.active && <button className="button secondary" type="button" onClick={() => void deactivate(item.id)}>DESATIVAR</button>}</li>)}</ul></div></div></section>;
}

export function AdminPrivacy() {
  const [items, setItems] = useState<Privacy[]>([]), [error, setError] = useState(""), [csrf, setCsrf] = useState("");
  async function load() { const [s, r] = await Promise.all([fetch("/api/v1/admin/auth/session", { credentials: "include" }), fetch("/api/v1/admin/privacy/requests", { credentials: "include", cache: "no-store" })]); const sp = await readApiEnvelope<{ csrf_token: string }>(s), p = await readApiEnvelope<Privacy[]>(r); if (!s.ok || !sp?.data) throw new Error(apiErrorMessage(sp, "Sessão expirada.")); if (!r.ok || !p?.data) throw new Error(apiErrorMessage(p, "Não foi possível carregar as solicitações.")); setCsrf(sp.data.csrf_token); setItems(p.data); }
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "Erro ao carregar.")); }, []);
  async function resolve(item: Privacy, status: string) { const response = await fetch(`/api/v1/admin/privacy/requests/${item.id}/status`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ status }) }); const p = await readApiEnvelope<Privacy>(response); if (!response.ok || !p?.data) return setError(apiErrorMessage(p, "Não foi possível atualizar a solicitação.")); setItems((current) => current.map((row) => row.id === item.id ? p.data! : row)); }
  return <section className={styles.section}><div className={styles.heading}><div><p className="eyebrow">Painel</p><h1>Privacidade</h1><p className="lead">Acompanhe solicitações LGPD sem expor a referência do titular.</p></div><button className="button secondary" type="button" onClick={() => void load()}>ATUALIZAR</button></div>{error && <div className="error-summary" role="alert">{error}</div>}{items.length ? <ul className={styles.list}>{items.map((item) => <li className={styles.item} key={item.id}><strong>{item.protocol}</strong><span>{item.request_type} · {item.status}</span><div><button className="button secondary" type="button" onClick={() => void resolve(item, "in_review")}>EM ANÁLISE</button>{" "}<button className="button secondary" type="button" onClick={() => void resolve(item, "resolved")}>RESOLVER</button></div></li>)}</ul> : <div className="empty">Nenhuma solicitação de privacidade registrada.</div>}</section>;
}
